<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="19" passed="15" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-20T15:15:52 IST" name="Default suite" finished-at="2024-12-20T15:18:37 IST" duration-ms="164599">
    <groups>
    </groups>
    <test started-at="2024-12-20T15:15:52 IST" name="Default test" finished-at="2024-12-20T15:18:37 IST" duration-ms="164599">
      <class name="loginTestCaseValidation.FacebookLoginValidation">
        <test-method signature="headingValidation()[pri:1, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:15:53 IST" name="headingValidation" finished-at="2024-12-20T15:16:00 IST" duration-ms="7585" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- headingValidation -->
        <test-method signature="subHeadingValidation()[pri:2, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:16:00 IST" name="subHeadingValidation" finished-at="2024-12-20T15:16:07 IST" duration-ms="6618" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Stay updated on your professional world.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Stay updated on your professional world.] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at loginTestCaseValidation.FacebookLoginValidation.subHeadingValidation(FacebookLoginValidation.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subHeadingValidation -->
        <test-method signature="validCredentialEmailPass()[pri:3, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:16:07 IST" name="validCredentialEmailPass" finished-at="2024-12-20T15:16:22 IST" duration-ms="14766" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentialEmailPass -->
        <test-method signature="invalidCredentialEmailPass()[pri:4, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:16:22 IST" name="invalidCredentialEmailPass" finished-at="2024-12-20T15:16:33 IST" duration-ms="11215" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidCredentialEmailPass -->
        <test-method signature="validPhonePass()[pri:5, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:16:33 IST" name="validPhonePass" finished-at="2024-12-20T15:16:40 IST" duration-ms="7507" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.linkedin.com/feed/?trk=guest_homepage-basic_nav-header-signin] but found [https://www.linkedin.com/checkpoint/lg/login-submit]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.linkedin.com/feed/?trk=guest_homepage-basic_nav-header-signin] but found [https://www.linkedin.com/checkpoint/lg/login-submit]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at loginTestCaseValidation.FacebookLoginValidation.validPhonePass(FacebookLoginValidation.java:108)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validPhonePass -->
        <test-method signature="validEmail_invalidPass()[pri:6, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:16:40 IST" name="validEmail_invalidPass" finished-at="2024-12-20T15:16:51 IST" duration-ms="10827" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validEmail_invalidPass -->
        <test-method signature="invalidEmail_validPass()[pri:7, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:16:51 IST" name="invalidEmail_validPass" finished-at="2024-12-20T15:17:05 IST" duration-ms="13906" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidEmail_validPass -->
        <test-method signature="invalidPhone_validPass()[pri:8, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:17:05 IST" name="invalidPhone_validPass" finished-at="2024-12-20T15:17:14 IST" duration-ms="8921" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidPhone_validPass -->
        <test-method signature="validPhone_invalidPass()[pri:9, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:17:14 IST" name="validPhone_invalidPass" finished-at="2024-12-20T15:17:23 IST" duration-ms="9296" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validPhone_invalidPass -->
        <test-method signature="validEmail_NoPass()[pri:10, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:17:23 IST" name="validEmail_NoPass" finished-at="2024-12-20T15:17:34 IST" duration-ms="10567" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validEmail_NoPass -->
        <test-method signature="validPhone_NoPass()[pri:11, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:17:34 IST" name="validPhone_NoPass" finished-at="2024-12-20T15:17:42 IST" duration-ms="8692" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validPhone_NoPass -->
        <test-method signature="noEmailNoPassCheck()[pri:12, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:17:42 IST" name="noEmailNoPassCheck" finished-at="2024-12-20T15:17:50 IST" duration-ms="7369" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noEmailNoPassCheck -->
        <test-method signature="invalidEmailFormatValidation()[pri:13, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:17:50 IST" name="invalidEmailFormatValidation" finished-at="2024-12-20T15:17:58 IST" duration-ms="7738" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidEmailFormatValidation -->
        <test-method signature="showPassbtn()[pri:14, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:17:58 IST" name="showPassbtn" finished-at="2024-12-20T15:18:07 IST" duration-ms="9259" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- showPassbtn -->
        <test-method signature="KeepmeLoggedinLabelCheck()[pri:15, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:18:07 IST" name="KeepmeLoggedinLabelCheck" finished-at="2024-12-20T15:18:13 IST" duration-ms="5974" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- KeepmeLoggedinLabelCheck -->
        <test-method signature="SignInButtonLabelCheck()[pri:16, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:18:13 IST" name="SignInButtonLabelCheck" finished-at="2024-12-20T15:18:18 IST" duration-ms="4997" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login] but found [Sign in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login] but found [Sign in]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at loginTestCaseValidation.FacebookLoginValidation.SignInButtonLabelCheck(FacebookLoginValidation.java:334)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignInButtonLabelCheck -->
        <test-method signature="EmailorPhoneLabelCheck()[pri:17, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:18:18 IST" name="EmailorPhoneLabelCheck" finished-at="2024-12-20T15:18:24 IST" duration-ms="6526" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmailorPhoneLabelCheck -->
        <test-method signature="PasswordLabelCheck()[pri:18, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:18:24 IST" name="PasswordLabelCheck" finished-at="2024-12-20T15:18:31 IST" duration-ms="7078" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PasswordLabelCheck -->
        <test-method signature="AppleSignInbtnLabelCheck()[pri:19, instance:loginTestCaseValidation.FacebookLoginValidation@7b36aa0c]" started-at="2024-12-20T15:18:31 IST" name="AppleSignInbtnLabelCheck" finished-at="2024-12-20T15:18:37 IST" duration-ms="5645" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sign in with Apple] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sign in with Apple] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at loginTestCaseValidation.FacebookLoginValidation.AppleSignInbtnLabelCheck(FacebookLoginValidation.java:382)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AppleSignInbtnLabelCheck -->
      </class> <!-- loginTestCaseValidation.FacebookLoginValidation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
